### ISSUE TITLE
Chosen js - add min-width to .chosen-container

### ISSUE THREAD

**Issue by n-langle** [sugarcalendar/core#111]
Hi @JJJ,

<img width="656" alt="Capture d’écran 2020-09-10 à 10 15 40" src="https://user-images.githubusercontent.com/28226882/92700317-fadce280-f34e-11ea-9358-6d019f1ae15a.png">

Can you add a min-width to .chosen-container to prevent line break ?

**Comment by JJJ** [comment]
There is a min-width of 55px set already. What browser are you using, and what font-size and zoom level are you using in it?

**Comment by n-langle** [comment]
My bad, for somes reasons we use an older version of sugar calendar 2.0.14. This fix was not present yet.
Thanks for your quick reply. I close this issue.
