### ISSUE TITLE
Events still display when moved to Trash

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#112]
When moving an Event to Trash, it still displays on the calendar view in admin and front-end. 

The event is in fact in the Trash as you will receive a "You can’t edit this item because it is in the Trash. Please restore it and try again." error in admin when trying to view the event as well as a 404 on the front-end.

**Comment by JJJ** [comment]
Regression introduced in b3522e332ac2784ec021ad361a9359b3484fe34a.

Pull request imminent.

**Comment by JJJ** [comment]
<img width="1020" alt="jjj-sc-2020-09-16 at 13 29 20@2x" src="https://user-images.githubusercontent.com/88951/93377492-ab9c2380-f820-11ea-9b0e-6c89d8ef7a48.png">

Above you'll see the Trash status accurately depicted, and the new "Restore" and "Delete" links in the pointer in Calendar views.
