### ISSUE TITLE
Taxonomy List Table (Calendars) too narrow to support future new columns from add-ons

### ISSUE THREAD

**Issue by JJJ** [sugarcalendar/core#123]
Calendars currently allow for colors, and the Calendar Feeds add-on adds a "View" column for looking at the feeds UI. With just those 2 extra columns, this UI is now basically full-up and over crowded, which leaves no room for future growth.

Specifically, this UI improvement will go a long way towards helping with ongoing Timezone work (for Advanced Recurring), as each individual Calendar will get its own Timezone that would be really nice to show as a list-table column.

**Comment by JJJ** [comment]
The solution I'm going to go with for 2.1.0 looks like this:

## List Table
<img width="1197" alt="jjj-sc-2020-10-06 at 17 22 47@2x" src="https://user-images.githubusercontent.com/88951/95266540-0231c780-07f9-11eb-9e4b-0b6d5b21721f.png">

## Add New Calendar
<img width="1197" alt="jjj-sc-2020-10-06 at 17 23 02@2x" src="https://user-images.githubusercontent.com/88951/95266561-137ad400-07f9-11eb-904e-851bbf794714.png">

## Why?

This uses a little bit of JavaScript and CSS to style the form side of the Taxonomy page as if it were a modal. The JavaScript is necessary to change the way the old "Add New" button works.

**Comment by JJJ** [comment]
@pippinsplugins You either need `define( 'SCRIPT_DEBUG', true );` or you need to run `grunt update`

**Comment by spencerfinnell** [comment]
@JJJ This is super cool, and a great solution to the space issue. Any thoughts on using jQuery UI Dialog to handle tab constraining and providing a close button?

**Comment by JJJ** [comment]
> Any thoughts on using jQuery UI Dialog to handle tab constraining and providing a close button?

If it's easier than mocking our own modal behavior, I'm all for it. 👍

**Comment by pippinsplugins** [comment]
SCRIPT_DEBUG is already set to true. I ran `grunt update` but I still see the same thing: old UI.

The Calendars URLs is still the same right? /wp-admin/edit-tags.php?taxonomy=sc_event_category&post_type=sc_event

**Comment by JJJ** [comment]
@pippinsplugins That is the correct URL.

Do you have JavaScript disabled in your browser?

**Comment by pippinsplugins** [comment]
No, JS is not disabled. Everything else works fine, I just seen the
standard WP taxonomy UI.

**Comment by JJJ** [comment]
@spencerfinnell Updated to use jQuery UI Dialog. There is one thing I don't _love_ about it: I can only specify width/height in pixels, so they aren't responsive. I measure the viewport and set the dimensions in a way to avoid them being larger than is sensible, which works OK.

## jQuery UI Dialog
<img width="1184" alt="jjj-sc-2020-10-07 at 13 51 03@2x" src="https://user-images.githubusercontent.com/88951/95374609-2bf3f880-08a4-11eb-943f-3b057fc73d8d.png">

**Comment by spencerfinnell** [comment]
@JJJ You should be able to apply CSS on the `create` callback: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/assets/js/admin/orders/order-overview/views/dialog.js#L34-L36

**Comment by spencerfinnell** [comment]
@JJJ Dialog works well! One last nice to have would be detecting `#tag-name` in the URL and opening the dialog if found. Right now if you open "Add Calendar" in a new tab you just land back on the same list table view.

**Comment by pippinsplugins** [comment]
@JJJ this works on my iMac!

Two things I'm seeing though:

1. The standard Add New Term fields show up for 1-2 seconds while the page loads then they vanish
2. There's a large white space where the form fields used to be
<img width="1913" alt="Screen Shot 2020-10-07 at 3 36 18 PM" src="https://user-images.githubusercontent.com/1034109/95384986-fb678b00-08b2-11eb-9af9-30b8f8c8a025.png">

**Comment by JJJ** [comment]
@spencerfinnell Added detection for `#tag-name` in the URL. Good idea!

Good suggestion on using `create()`. Works like it should!

@pippinsplugins Is `sc-taxonomy.css` not being enqueued? It looks like you're missing all of the styling.

**Comment by pippinsplugins** [comment]
@JJJ it is loaded and the file contents are there.

**Comment by JJJ** [comment]
@pippinsplugins what version of WordPress?

**Comment by pippinsplugins** [comment]
5.5.1.

I just updated to latest trunk and same thing.

**Comment by JJJ** [comment]
@pippinsplugins something unrelated to this issue appears to be broken on your installation(s) and is causing other issues. Styling from `sc-nav.css` - which is unchanged in this issue - is also not being applied. It should be hiding the "Calendars" `h1` on that page, but in your screenshot it is visible.

**Comment by pippinsplugins** [comment]
@JJJ found the conflict. It's WooCommerce. Deactivating WooCommerce makes everything work as expected.

That'll be a conflict we have to fix on our end.

**Comment by JJJ** [comment]
Looks like WooCommerce is blowing away our body class. One of us is misusing the `admin_body_class` filter someplace.

**Comment by JJJ** [comment]
Pull down the PR. WooCommerce conflict fixed.

**Comment by JJJ** [comment]
PR merged into 2.1.0 branch. Calling this initiative done. Thanks Spencer and Pippin for testing, feedback, and ideas! 💪

**Comment by pippinsplugins** [comment]
@JJJ works great now for me!
