### ISSUE TITLE
Calendars taxonomy not appearing in Gutenberg

### ISSUE THREAD

**Issue by JJJ** [sugarcalendar/core#127]
Reported via HelpScout, a non-Lite customer noticed that the Calendars UI is missing when using the block editor option.

This is not intended, and should be remedied pretty quickly.

The major hurdle with this, is identifying if it is possible to override this output, or whether we need to introduce our own UI for it. By simply using `show_in_rest` we can make it appear, but Events can only belong to one Calendar at a time, but WordPress always uses checkboxes, whereas we override that meta-box output and Walker to use radios instead - that old code doesn't transfer to this UI.

<img width="1202" alt="jjj-sc-2020-10-09 at 00 55 24@2x" src="https://user-images.githubusercontent.com/88951/95548170-25f83780-09ca-11eb-95ee-c8324019963c.png">

**Comment by shaynesanderson** [comment]
Another customer reporting this issue: https://secure.helpscout.net/conversation/1543587038/187216?folderId=1909447

**Comment by JJJ** [comment]
Merged & fixed!
