### ISSUE TITLE
Add option to show "all dates" in list view

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#129]
### Add option to show "All Dates" in list view. 

Currently Sugar Calendar gives the option to show "All Calendars" but only for a particular year at a time. When using List View (as this wouldn't make sense for other views), this would work similar to how Posts/Pages screens currently work with the "All Dates" option. 

<img width="705" alt="Screen Shot 2020-10-22 at 10 02 56" src="https://user-images.githubusercontent.com/1680163/96890965-ced47700-144d-11eb-8f62-40f8ac519b7f.png">

### Justification or use case
When viewing all events (bulk editing maybe), this would be a useful.

Customer request: https://secure.helpscout.net/conversation/1315978189/168548?folderId=3668573

**Comment by JJJ** [comment]
Merged & closing.
