### ISSUE TITLE
Time Format incorrect

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#144]
## Bug Report

When setting a custom time format in "Calendar-->Settings-->Display", the timezone abbreviations do not work as expected. 

Example:

Settings time format to g:i a T results in GMT +0000 being added opposed to CST, EST, etc. 

Note: This is also affected on the front-end display.

![Screenshot_2020-12-09 Settings ‹ Italian Art Society — WordPress](https://user-images.githubusercontent.com/1680163/101667607-25553f00-3a15-11eb-937f-a56a634f5e10.png)

**Comment by JJJ** [comment]
Fixed & merged.
