### ISSUE TITLE
Weekly view incorrect when starting week with Monday

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#154]
## Bug Report

When selecting "Monday" as the start of the week in "Calendar-->Settings-->Display", the weekly view is wrong (shown below regular calendar in screenshot). 

![Screenshot_2021-01-04 Calendar – SC TEST(1)](https://user-images.githubusercontent.com/1680163/103554712-f778e400-4e74-11eb-93ad-e8c219cabbaa.png)

Setting to "Sunday" as the start day, things work as expected.

Also, setting the start day to anything besides Sunday or Monday has no effect on the calendar.

**Comment by JJJ** [comment]
Merged and closing. 💫

Thanks @shaynesanderson for the detailed bug report!
