### ISSUE TITLE
Dropdown month selection not working

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#168]
## Bug Report

When viewing the calendar on the front-end and selecting a month in the dropdown and clicking "Go" it does not display the correct month. Then clicking "Previous" does display the correct month. 

Example: 

Choose "February" from dropdown and click "Go". You'll see the title changes to February but the calendar is for March.
![Screenshot_2021-01-29 Calendar – SC TEST](https://user-images.githubusercontent.com/1680163/106292109-13706b00-6212-11eb-83cc-c29940715809.png)

From there, click the "Previous" button and you'll see the title stays February but the calendar is correctly showing February.
![Screenshot_2021-01-29 Calendar – SC TEST(1)](https://user-images.githubusercontent.com/1680163/106292217-2daa4900-6212-11eb-87dc-416e53e14a59.png)

**Comment by JJJ** [comment]
Fixed! Will be packaged in the 2.1.6 release. 🛠
