### ISSUE TITLE
Event not saved if event time zone doesn't match site time zone

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#180]
## Bug Report

If the time zone set in "Settings-->General" does not match the time zone set in "Calendar-->Settings-->Time Zones-->Default Time Zone (when using Single or Multi option)" then the information does not save. 

The event technically saves but it does not show on the calendar and when looking at the refreshed event page after saving, the date is missing. 

![Screenshot_2021-03-01 Edit Event ‹ SC TEST — WordPress](https://user-images.githubusercontent.com/1680163/109551413-23d86780-7a96-11eb-9f17-4ed6efe08444.png)

**Comment by JJJ** [comment]
Hey @shaynesanderson! Can I get more information on this one?

This is all working OK for me:

## Settings -> General
<img width="910" alt="jjj-on-2021-03-05-at-10-07-40@2x" src="https://user-images.githubusercontent.com/88951/110141368-afa20a80-7d9a-11eb-90da-3b33bd8ee04e.png">

## Calendar -> Settings -> Time Zones
<img width="812" alt="jjj-on-2021-03-05-at-10-07-24@2x" src="https://user-images.githubusercontent.com/88951/110141392-b761af00-7d9a-11eb-8f21-999ea563a2ba.png">

## Event
<img width="767" alt="jjj-on-2021-03-05-at-10-06-59@2x" src="https://user-images.githubusercontent.com/88951/110141468-cc3e4280-7d9a-11eb-82c8-6ecc24eb5eff.png">

<img width="348" alt="jjj-on-2021-03-05-at-10-09-04@2x" src="https://user-images.githubusercontent.com/88951/110141521-d82a0480-7d9a-11eb-8bf9-5693b43f0474.png">

# Maybe Related

In your screenshot, it looks like some of the CSS isn't loaded. The Chosen drop-downs should look like they do in my screenshots, no matter what operating system or browser (except for mobile). Do they always look like that for you?

**Comment by shaynesanderson** [comment]
@JJJ You're right, it was actually EDD that was causing the CSS issue. When EDD is deactivated, it appears normally and is saving correctly as well.
