### ISSUE TITLE
Single Events 404 on new install

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#186]
## Bug Report

Upon a new installation of either the Lite or Pro version and setting up events, etc viewing a single event results in a 404. Permalinks have to be re-saved in order to view the page correctly.

**Comment by JJJ** [comment]
Related WordPress Core Issue: https://core.trac.wordpress.org/ticket/47686

I was hoping we wouldn't need to do this ourselves, but I'll get it done ASAP for 2.1.9. 👍

**Comment by shaynesanderson** [comment]
Gotcha. That is silly that it's in issue in WP but thank you!

**Comment by JJJ** [comment]
Fixed for 2.1.9.
