### ISSUE TITLE
Extra space in CPT slug

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#190]
## Bug Report

In version 2.1.9, the "events" slug has an extra space. 

<code>define( 'SC_EVENTS_SLUG', 'events ')</code>

It's not breaking pages for me but customer is reporting that it is. 

Reference: https://secure.helpscout.net/conversation/1477989293/182026?folderId=1909447

**Comment by JJJ** [comment]
Will be fixed in 2.1.10.
