### ISSUE TITLE
WordPress 5.8: Fatal erroring on new Admin > Widgets page

### ISSUE THREAD

**Issue by JJJ** [sugarcalendar/core#227]
Because it got rammed through in the last minute, as is tradition, the WordPress 5.8 widgets screen is causing a fatal error due to the way Sugar Calendar registers (and now tries to preview) its widgets.

Details TBD.

<img width="707" alt="jjj-on-2021-07-21-at-19-39-26@2x" src="https://user-images.githubusercontent.com/88951/126576545-1021096a-bf74-46c4-9417-f6a03e2c8acb.png">

**Comment by JJJ** [comment]
![jjj-on-2021-07-21-at-19-49-06@2x](https://user-images.githubusercontent.com/88951/126576996-b09aeaa9-6570-46dc-9835-2b44975c7361.png)

😡

**Comment by spencerfinnell** [comment]
Maybe related: https://github.com/WordPress/gutenberg/issues/33443

**Comment by JJJ** [comment]
https://github.com/sugarcalendar/core/blob/7155c47aa1925c35ec33729ee55d31ba6629d21e/sugar-calendar/sugar-calendar.php#L252-L268

**Comment by JJJ** [comment]
Thanks @spencerfinnell for the research there. Much appreciated.

Sugar Calendar is affected by this because it uses an `is_admin()` check to avoid including a few Legacy PHP files that have functions in theme that were never intended to be called inside of WordPress Admin.

On the new Widgets page, it's partially live-previewing widget areas but with `WP_ADMIN` set and `WP_USE_THEMES` null, so the theme-side output functions in Sugar Calendar aren't available.

I guess the fix on our end is simply to always include everything now?
