### ISSUE TITLE
Deprecated PHP function used in Event List view

### ISSUE THREAD

**Issue by joelyoder** [sugarcalendar/core#230]
I noticed a PHP error when using the `[sc_events_list show_date='yes' show_time='yes' show_categories='yes' show_link='yes']` shortcode on my testbench with `WP_debug` enabled.

After the date, this error is appearing in the post content:
`Deprecated: implode(): Passing glue string after array is deprecated. Swap the parameters in /srv/www/wordpress-one/public_html/wp-content/plugins/sugar-calendar-lite/sugar-calendar/includes/themes/legacy/events-list.php on line 200`

My site is running WordPress 5.8 and PHP 7.4. This function is [partially deprecated in PHP 7.4 and fully deprecated in PHP 8](https://www.php.net/manual/en/function.implode.php), so it would be a good idea to replace it entirely before PHP 8 ships.

This site is a clean install.
**Theme:** Twenty Ninteen
**Plugins:**
- Debug Bar
- Query Monitor
- Sugar Calendar (Lite)
- Sugar Calendar Customizer
- WP Debugging

**Comment by JJJ** [comment]
Thank you @joelyoder 🙏 Will be fixed in the next minor release. 👍
