### ISSUE TITLE
Update from 1.6.8 removes end date

### ISSUE THREAD

**Issue by shaynesanderson** [sugarcalendar/core#231]
## Bug Report

This is in regards to the Lite version, although it would happen moving from Lite to Pro as well. 

When using Lite 1.6.8 and having events in place, after updating to the current version (2.2.3), while the event start date stays in place, the end dates are no longer shown on events.

**Comment by JJJ** [comment]
Looks like this regressed in 2.2.1, here specifically: b72919a
