### ISSUE TITLE
sc_get_events_list() returns past events when getting upcoming

### ISSUE THREAD

**Issue by JiveDig** [sugarcalendar/core#44]
I have an event that starts today at 12pm (EST/New York set in WP), and ends at 2pm.

Expected behavior using `[sc_events_list display="upcoming"]`:
The event would show as upcoming until it starts or until it is over.

Expected behavior using `[sc_events_list display="past"]`:
The event would show as past once it is over (to the minute/second).

Actual behavior using `[sc_events_list display="upcoming"]`:
The event is still showing as upcoming, even 2 hours after the event is over.

Actual behavior using `[sc_events_list display="past"]`:
The event has been showing as a past event since we checked it this morning.

**Comment by JJJ** [comment]
Hey @JiveDig! I see what you're saying, and it makes sense.

Right now, the shortcode is inclusive of the entire day, and the boundaries aren't exposed as via shortcode attributes or parameters to tweak them.

I'll give this a think and make sure we address it in the next release!

**Comment by JJJ** [comment]
Fixed for 2.1.0.
