### ISSUE TITLE
Dutch translation strings requested in default.po file

### ISSUE THREAD

**Issue by gspice** [sugarcalendar/core#54]
Reported from HS ticket:
https://secure.helpscout.net/conversation/647066685/88460?folderId=1909468

>...the Dutch translation of the plugin contains the following issues:
>- The admin pages for creating/editing a calendar item displays an AM/PM selection option. In the Dutch language we don't use AM/PM, instead we use the 24-hour time format.
>- The date format on the single calendar item page is 'MONTHNAME DATE, YEAR' instead of the usual Dutch format 'DATE MONTHNAME YEAR'. The settings of the plugin also don't allow me to select an other format which is usually used in Dutch like 'DATE-MONTH-YEAR'.
>- The time format on the single calendar item page contains two spaces instead of one before and after the word 'tot' (the Dutch word for 'until'), for example '10:00 tot 17:00'.
>- The date range on the single calendar item page is not fully translated (only the month/weekday names are translated). For example: 'Starts augustus 8, 2018 then every woensdag' instead of 'Start 8 augustus 2018, daarna elke woensdag'. I've already looked into the translation file but I couldn't find a field to add this translation to.

**Comment by JJJ** [comment]
All of the technical issues have been resolved, and a Dutch translation now exists on WordPress.org that anyone can contribute to!

https://translate.wordpress.org/locale/nl/default/wp-plugins/sugar-calendar-lite/
