### ISSUE TITLE
Add "Duplicate Event" functionality to make copying events easy

### ISSUE THREAD

**Issue by gspice** [sugarcalendar/core#60]
**To reproduce the issue:**

* Installed the plugin Duplicate Post from the WP.org repo as I do on most of my test sites to easily duplicate data https://wordpress.org/plugins/duplicate-post/
* Navigated to the plugin settings to enable the post type `Calendar` 
* Hover over an existing event on my list, click the `Clone` link 
* Results were: the screen refreshes but no new calendar event was created

**Expected behavior:**

With previous version 1.6.x, you would receive a duplicate event in `Draft` status.

**Comment by thisisjoewells** [comment]
Plus one on this request, I forgot to log it here, but saw it reviewing my notes today.

One of many very positive reviews on Capterra from 4/6/20, and this was requested:

> Always have a wish or two in waiting, don't we all? I wish I could duplicate events...

**Comment by shaynesanderson** [comment]
Another request: https://secure.helpscout.net/conversation/1296733452/166981?folderId=1909447
