### ISSUE TITLE
Admin: 24 hour option not recognized when scheduling an event

### ISSUE THREAD

**Issue by gspice** [sugarcalendar/core#64]
Reported on this HS ticket about the same time I noticed it in testing.  I happen to use a 24hr clock on all my time-things:
https://secure.helpscout.net/conversation/829226730/118230/?folderId=1909468

My **Screen Options** settings match my _Calendar > Settings > Display_: 

<img width="467" alt="screen-options" src="https://user-images.githubusercontent.com/3018245/56436780-de3f9680-6291-11e9-986b-71c2e1ae5a76.png">

When creating or editing an event, the edit screen doesn't show the 24-hour hourly digits. Instead it shows 01-12 and AM/PM:

<img width="891" alt="add-edit-event-24-hr" src="https://user-images.githubusercontent.com/3018245/56436920-69b92780-6292-11e9-9af8-9ab7d6692c11.png">

The same event _does_ show correct on the frontend when published/updated:

<img width="1128" alt="published-fronend-viewpng" src="https://user-images.githubusercontent.com/3018245/56436948-7ccbf780-6292-11e9-98ad-669dd4f386ab.png">

**Comment by JJJ** [comment]
Fixed in #100
