### ISSUE TITLE
Possible conflict with WP-Ultimo 

### ISSUE THREAD

**Issue by gspice** [sugarcalendar/core#68]
Reported on this HS ticket:
https://secure.helpscout.net/conversation/953591490/131195/

User on WordPress Multisite and reported a plugin conflict with WP-Ultimo.  He was not able to change the start day of the week option in Sugar Calendar settings.  It would revert back to the default after he clicked to save.  Also had an error when clicking on the update database link.  When he deactivated WP-Ultimo, all features worked correctly.  This is just an FYI for the future, we do not currently have a copy of WP-Ultimo to test with, but I'm not sure we need to at this point.

**Comment by JJJ** [comment]
This issue remains unresolved, but it's seeming less and less likely that we will get around to it, so I'm going to close this out.

Feel free to reopen if this becomes a priority.
