### ISSUE TITLE
Add support for entering license key in wp-config.php

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/core#69]
We've had a [customer request](https://secure.helpscout.net/conversation/1012128804/137551?folderId=1909447) the ability to enter their license key inside of wp-config.php.

We've done this in AffiliateWP and it works really well.

Related: sugarcalendar/core#53

**Comment by JJJ** [comment]
Fixed side-stream in the Standard repository, for 2.1.9.
