### ISSUE TITLE
Add ability to use custom fields in event content

### ISSUE THREAD

**Issue by gspice** [sugarcalendar/core#71]
We've had some HS tickets requesting the use of custom fields in their events.  Some are using ACF and some are using Beaver Themer. 

These are the tickets I found using search, I'll keep adding as they come in :

https://secure.helpscout.net/conversation/590601088/83184/
https://secure.helpscout.net/conversation/925524308/127346/
https://secure.helpscout.net/conversation/953994129/131243/
https://secure.helpscout.net/conversation/1024910507/139264/
https://secure.helpscout.net/conversation/1025564695/139346/

**Comment by JJJ** [comment]
Done for 2.1.0.
